In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

pd.set_option("display.max_columns", None)

data_path = Path(
    r"C:\Users\GIA NGUYEN\OneDrive\Máy tính\Ecommerce_Olist_Analysis\data\raw"
)

customers = pd.read_csv(data_path / "olist_customers_dataset.csv")
orders = pd.read_csv(data_path / "olist_orders_dataset.csv")
order_items = pd.read_csv(data_path / "olist_order_items_dataset.csv")
payments = pd.read_csv(data_path / "olist_order_payments_dataset.csv")
reviews = pd.read_csv(data_path / "olist_order_reviews_dataset.csv")
products = pd.read_csv(data_path / "olist_products_dataset.csv")
sellers = pd.read_csv(data_path / "olist_sellers_dataset.csv")
geolocation = pd.read_csv(data_path / "olist_geolocation_dataset.csv")
category_translation = pd.read_csv(
    data_path / "product_category_name_translation.csv"
)

print("Customers:", customers.shape)
print("Orders:", orders.shape)
print("Order items:", order_items.shape)
print("Payments:", payments.shape)
print("Reviews:", reviews.shape)
print("Products:", products.shape)
print("Sellers:", sellers.shape)
print("Geolocation:", geolocation.shape)
print("Category translation:", category_translation.shape)

Customers: (99441, 5)
Orders: (99441, 8)
Order items: (112650, 7)
Payments: (103886, 5)
Reviews: (99224, 7)
Products: (32951, 9)
Sellers: (3095, 4)
Geolocation: (1000163, 5)
Category translation: (71, 2)

In [4]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [10]:
datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "products": products,
    "sellers": sellers,
    "geolocation": geolocation,
    "category_translation": category_translation
}

for name, df in datasets.items():
    print(f"\n===== {name.upper()} =====")
    print("Số dòng, số cột:", df.shape)
    print("Danh sách cột:")
    print(df.columns.tolist())

===== CUSTOMERS =====
Số dòng, số cột: (99441, 5)
Danh sách cột:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

===== ORDERS =====
Số dòng, số cột: (99441, 8)
Danh sách cột:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

===== ORDER_ITEMS =====
Số dòng, số cột: (112650, 7)
Danh sách cột:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

===== PAYMENTS =====
Số dòng, số cột: (103886, 5)
Danh sách cột:
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

===== REVIEWS =====
Số dòng, số cột: (99224, 7)
Danh sách cột:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

===== PRODUCTS =====
Số dòng, số cột: (32951, 9)
Danh sách cột:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

===== SELLERS =====
Số dòng, số cột: (3095, 4)
Danh sách cột:
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

===== GEOLOCATION =====
Số dòng, số cột: (1000163, 5)
Danh sách cột:
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

===== CATEGORY_TRANSLATION =====
Số dòng, số cột: (71, 2)
Danh sách cột:
['product_category_name', 'product_category_name_english']

In [11]:
for name, df in datasets.items():
    print(f"\n===== {name.upper()} =====")
    display(df.head(3))

===== CUSTOMERS =====

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP

===== ORDERS =====

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00

===== ORDER_ITEMS =====

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.0,17.87

===== PAYMENTS =====

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71

===== REVIEWS =====

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24

===== PRODUCTS =====

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0

===== SELLERS =====

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ

===== GEOLOCATION =====

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP

===== CATEGORY_TRANSLATION =====

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto

In [12]:
key_checks = {
    "customers.customer_id": customers["customer_id"].nunique(),
    "customers.customer_unique_id": customers["customer_unique_id"].nunique(),
    "orders.order_id": orders["order_id"].nunique(),
    "orders.customer_id": orders["customer_id"].nunique(),
    "order_items.order_id": order_items["order_id"].nunique(),
    "order_items.product_id": order_items["product_id"].nunique(),
    "order_items.seller_id": order_items["seller_id"].nunique(),
    "payments.order_id": payments["order_id"].nunique(),
    "reviews.order_id": reviews["order_id"].nunique(),
    "products.product_id": products["product_id"].nunique(),
    "sellers.seller_id": sellers["seller_id"].nunique()
}

for key, value in key_checks.items():
    print(f"{key}: {value:,}")

customers.customer_id: 99,441
customers.customer_unique_id: 96,096
orders.order_id: 99,441
orders.customer_id: 99,441
order_items.order_id: 98,666
order_items.product_id: 32,951
order_items.seller_id: 3,095
payments.order_id: 99,440
reviews.order_id: 98,673
products.product_id: 32,951
sellers.seller_id: 3,095

In [13]:
primary_key_checks = {
    "customers.customer_id": customers["customer_id"].duplicated().sum(),
    "orders.order_id": orders["order_id"].duplicated().sum(),
    "products.product_id": products["product_id"].duplicated().sum(),
    "sellers.seller_id": sellers["seller_id"].duplicated().sum()
}

for key, duplicates in primary_key_checks.items():
    print(f"{key} - số giá trị trùng: {duplicates}")

customers.customer_id - số giá trị trùng: 0
orders.order_id - số giá trị trùng: 0
products.product_id - số giá trị trùng: 0
sellers.seller_id - số giá trị trùng: 0

In [14]:
for name, df in datasets.items():
    print(f"\n====={name.upper()} =====")
    df.info()

=====CUSTOMERS =====
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

=====ORDERS =====
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

=====ORDER_ITEMS =====
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

=====PAYMENTS =====
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

=====REVIEWS =====
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

=====PRODUCTS =====
<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

=====SELLERS =====
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

=====GEOLOCATION =====
<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB

=====CATEGORY_TRANSLATION =====
<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

In [16]:
missing_reports = []

for name, df in datasets.items():
    missing_count = df.isnull().sum()
    missing_percent = (missing_count / len(df) * 100).round(2)

    report = pd.DataFrame({
        "table": name,
        "column": df.columns,
        "missing_count": missing_count.values,
        "missing_percent": missing_percent.values
    })

    report = report[report["missing_count"] > 0]
    missing_reports.append(report)

missing_report = pd.concat(missing_reports, ignore_index=True)

missing_report.sort_values(
    by="missing_percent",
    ascending=False
)

       table                         column  missing_count  missing_percent
3    reviews           review_comment_title          87656            88.34
4    reviews         review_comment_message          58247            58.70
2     orders  order_delivered_customer_date           2965             2.98
6   products            product_name_lenght            610             1.85
5   products          product_category_name            610             1.85
7   products     product_description_lenght            610             1.85
8   products             product_photos_qty            610             1.85
1     orders   order_delivered_carrier_date           1783             1.79
0     orders              order_approved_at            160             0.16
9   products               product_weight_g              2             0.01
10  products              product_length_cm              2             0.01
11  products              product_height_cm              2             0.01
12  products               product_width_cm              2             0.01

In [17]:
duplicate_report = [] 

for name, df in datasets.items():
    duplicate_count = df.duplicated().sum()

    duplicate_report.append({
        "table": name,
        "total_rows": len(df),
        "duplicate_rows": duplicate_count,
        "duplicate_percent": round(
            duplicate_count / len(df) * 100, 2
        )
    })
duplicate_report = pd.DataFrame(duplicate_report)
duplicate_report

                  table  total_rows  duplicate_rows  duplicate_percent
0             customers       99441               0               0.00
1                orders       99441               0               0.00
2           order_items      112650               0               0.00
3              payments      103886               0               0.00
4               reviews       99224               0               0.00
5              products       32951               0               0.00
6               sellers        3095               0               0.00
7           geolocation     1000163          261831              26.18
8  category_translation          71               0               0.00

In [19]:
orders["order_status"].value_counts(dropna=False)

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [20]:
orders["order_status"].value_counts(
    normalize=True,
    dropna=False
).mul(100).round(2)

order_status
delivered      97.02
shipped         1.11
canceled        0.63
unavailable     0.61
invoiced        0.32
processing      0.30
created         0.01
approved        0.00
Name: proportion, dtype: float64

In [21]:
print("===== ORDER ITEMS =====")
display(order_items[["price", "freight_value"]].describe())

print("===== PAYMENTS =====")
display(
    payments[
        ["payment_sequential", "payment_installments", "payment_value"]
    ].describe()
)

print("===== REVIEWS =====")
display(reviews["review_score"].describe())

===== ORDER ITEMS =====

               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000

===== PAYMENTS =====

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

===== REVIEWS =====

count    99224.000000
mean         4.086421
std          1.347579
min          1.000000
25%          4.000000
50%          5.000000
75%          5.000000
max          5.000000
Name: review_score, dtype: float64

In [22]:
print("Price <= 0:", (order_items["price"] <= 0).sum())

print(
    "Freight value < 0:",
    (order_items["freight_value"] < 0).sum()
)

print(
    "Payment value <= 0:",
    (payments["payment_value"] <= 0).sum()
)

print(
    "Invalid review scores:",
    (~reviews["review_score"].between(1, 5)).sum()
)

Price <= 0: 0
Freight value < 0: 0
Payment value <= 0: 9
Invalid review scores: 0